
name: Github Actions NS3886

on:
  push:
    branches: ["dev_github_actions","github_actions_to_merge"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        id: build
        working-directory: ./IndividualProject
        run: mvn -B package --file pom.xml
      - name: Run JUnit tests and verify with Maven
        working-directory: ./IndividualProject
        run: mvn clean test package verify
      - name: Fail build if there are violations
        if: steps.build.outputs.violations != 0
        run: exit 1
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: >
            IndividualProject/target/site/jacoco/jacoco.csv
      #- name: style check
       # id: style_check
        #working-directory: ./IndividualProject
        #run: mvn checkstyle:check
      #- name: Fail build if there are violation
        #run: exit 1
      - uses: pmd/pmd-github-action@v2
        id: pmd
        with:
          version: '6.55.0'
          sourcePath: 'IndividualProject/src/main/java'
          rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'
      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1







